### ISSUE TITLE
I cannot run any yarn command because of this error "E2BIG"

### ISSUE THREAD

**Issue by xyzt1402** [splunk/SUIT-example-for-visualizations#9]
This is my yarn error log
`Yarn version: 
  1.22.19

Node version: 
  16.18.1

Platform: 
  linux x64

Trace: 
  Error: spawn E2BIG
      at ChildProcess.spawn (node:internal/child_process:420:11)
      at Object.spawn (node:child_process:733:9)
      at /usr/share/yarn/lib/cli.js:25732:24
      at new Promise (<anonymous>)
      at new F (/usr/share/yarn/lib/cli.js:5305:28)
      at /usr/share/yarn/lib/cli.js:25729:12
      at run (/usr/share/yarn/lib/cli.js:43184:7)
      at BlockingQueue.maybePushConcurrencyQueue (/usr/share/yarn/lib/cli.js:43199:7)
      at BlockingQueue.shift (/usr/share/yarn/lib/cli.js:43194:10)
      at /usr/share/yarn/lib/cli.js:43138:15`

**Comment by spmml** [comment]
I faced the same issue. 
My solution was:

1. Renaming `NOTICE.csv` into `NOTICE_backup.csv`
2. Removing of `yarn.lock`: `rm -rf yarn.lock`
3. Removing of `node_modules`: `rm -rf node_modules`
4. Editing `SUIT-example-for-visualizations/packages/sui-visualizations-example/src/main/webapp/pages/start/index.jsx`:
There is one import with wrong lower/upper case combination:` import ThirdPartyExample from '../3PwithoutDF/3PwithoutDF';`
5. `yarn install` in the `SUIT-example-for-visualizations` directory
6. `yarn run build`  in the `SUIT-example-for-visualizations` directory
7. `yarn run link:app` in the `SUIT-example-for-visualizations/packages/sui-visualizations-example` directory
8. `yarn run start` in the `SUIT-example-for-visualizations` directory

I am not sure if all steps are necessary (especially  2-3), but it worked for me.

Node Version: 18.17.1
Yarn Version: 1.22.19
Platform: Linux x64
